package ww.greendao.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import ww.greendao.dao.Classes;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CLASSES.
*/
public class ClassesDao extends AbstractDao<Classes, Long> {

    public static final String TABLENAME = "CLASSES";

    /**
     * Properties of entity Classes.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ClassID = new Property(0, Long.class, "ClassID", true, "CLASS_ID");
        public final static Property GradeID = new Property(1, long.class, "GradeID", false, "GRADE_ID");
        public final static Property ClassCode = new Property(2, String.class, "ClassCode", false, "CLASS_CODE");
        public final static Property ClassName = new Property(3, String.class, "ClassName", false, "CLASS_NAME");
        public final static Property Remark1 = new Property(4, String.class, "Remark1", false, "REMARK1");
    };

    private DaoSession daoSession;

    private Query<Classes> grade_AllClassQuery;

    public ClassesDao(DaoConfig config) {
        super(config);
    }
    
    public ClassesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CLASSES' (" + //
                "'CLASS_ID' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: ClassID
                "'GRADE_ID' INTEGER NOT NULL ," + // 1: GradeID
                "'CLASS_CODE' TEXT UNIQUE ," + // 2: ClassCode
                "'CLASS_NAME' TEXT," + // 3: ClassName
                "'REMARK1' TEXT);"); // 4: Remark1
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CLASSES'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Classes entity) {
        stmt.clearBindings();
 
        Long ClassID = entity.getClassID();
        if (ClassID != null) {
            stmt.bindLong(1, ClassID);
        }
        stmt.bindLong(2, entity.getGradeID());
 
        String ClassCode = entity.getClassCode();
        if (ClassCode != null) {
            stmt.bindString(3, ClassCode);
        }
 
        String ClassName = entity.getClassName();
        if (ClassName != null) {
            stmt.bindString(4, ClassName);
        }
 
        String Remark1 = entity.getRemark1();
        if (Remark1 != null) {
            stmt.bindString(5, Remark1);
        }
    }

    @Override
    protected void attachEntity(Classes entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Classes readEntity(Cursor cursor, int offset) {
        Classes entity = new Classes( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ClassID
            cursor.getLong(offset + 1), // GradeID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ClassCode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ClassName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // Remark1
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Classes entity, int offset) {
        entity.setClassID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGradeID(cursor.getLong(offset + 1));
        entity.setClassCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setClassName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRemark1(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Classes entity, long rowId) {
        entity.setClassID(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Classes entity) {
        if(entity != null) {
            return entity.getClassID();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "allClass" to-many relationship of Grade. */
    public List<Classes> _queryGrade_AllClass(long GradeID) {
        synchronized (this) {
            if (grade_AllClassQuery == null) {
                QueryBuilder<Classes> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.GradeID.eq(null));
                grade_AllClassQuery = queryBuilder.build();
            }
        }
        Query<Classes> query = grade_AllClassQuery.forCurrentThread();
        query.setParameter(0, GradeID);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getGradeDao().getAllColumns());
            builder.append(" FROM CLASSES T");
            builder.append(" LEFT JOIN GRADE T0 ON T.'GRADE_ID'=T0.'GRADE_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Classes loadCurrentDeep(Cursor cursor, boolean lock) {
        Classes entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Grade grade = loadCurrentOther(daoSession.getGradeDao(), cursor, offset);
         if(grade != null) {
            entity.setGrade(grade);
        }

        return entity;    
    }

    public Classes loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Classes> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Classes> list = new ArrayList<Classes>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Classes> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Classes> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
