package ww.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import ww.greendao.dao.Item;
import ww.greendao.dao.School;
import ww.greendao.dao.Grade;
import ww.greendao.dao.Classes;
import ww.greendao.dao.Student;
import ww.greendao.dao.StudentItem;
import ww.greendao.dao.RoundResult;

import ww.greendao.dao.ItemDao;
import ww.greendao.dao.SchoolDao;
import ww.greendao.dao.GradeDao;
import ww.greendao.dao.ClassesDao;
import ww.greendao.dao.StudentDao;
import ww.greendao.dao.StudentItemDao;
import ww.greendao.dao.RoundResultDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig itemDaoConfig;
    private final DaoConfig schoolDaoConfig;
    private final DaoConfig gradeDaoConfig;
    private final DaoConfig classesDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig studentItemDaoConfig;
    private final DaoConfig roundResultDaoConfig;

    private final ItemDao itemDao;
    private final SchoolDao schoolDao;
    private final GradeDao gradeDao;
    private final ClassesDao classesDao;
    private final StudentDao studentDao;
    private final StudentItemDao studentItemDao;
    private final RoundResultDao roundResultDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        schoolDaoConfig = daoConfigMap.get(SchoolDao.class).clone();
        schoolDaoConfig.initIdentityScope(type);

        gradeDaoConfig = daoConfigMap.get(GradeDao.class).clone();
        gradeDaoConfig.initIdentityScope(type);

        classesDaoConfig = daoConfigMap.get(ClassesDao.class).clone();
        classesDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        studentItemDaoConfig = daoConfigMap.get(StudentItemDao.class).clone();
        studentItemDaoConfig.initIdentityScope(type);

        roundResultDaoConfig = daoConfigMap.get(RoundResultDao.class).clone();
        roundResultDaoConfig.initIdentityScope(type);

        itemDao = new ItemDao(itemDaoConfig, this);
        schoolDao = new SchoolDao(schoolDaoConfig, this);
        gradeDao = new GradeDao(gradeDaoConfig, this);
        classesDao = new ClassesDao(classesDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        studentItemDao = new StudentItemDao(studentItemDaoConfig, this);
        roundResultDao = new RoundResultDao(roundResultDaoConfig, this);

        registerDao(Item.class, itemDao);
        registerDao(School.class, schoolDao);
        registerDao(Grade.class, gradeDao);
        registerDao(Classes.class, classesDao);
        registerDao(Student.class, studentDao);
        registerDao(StudentItem.class, studentItemDao);
        registerDao(RoundResult.class, roundResultDao);
    }
    
    public void clear() {
        itemDaoConfig.getIdentityScope().clear();
        schoolDaoConfig.getIdentityScope().clear();
        gradeDaoConfig.getIdentityScope().clear();
        classesDaoConfig.getIdentityScope().clear();
        studentDaoConfig.getIdentityScope().clear();
        studentItemDaoConfig.getIdentityScope().clear();
        roundResultDaoConfig.getIdentityScope().clear();
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

    public SchoolDao getSchoolDao() {
        return schoolDao;
    }

    public GradeDao getGradeDao() {
        return gradeDao;
    }

    public ClassesDao getClassesDao() {
        return classesDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public StudentItemDao getStudentItemDao() {
        return studentItemDao;
    }

    public RoundResultDao getRoundResultDao() {
        return roundResultDao;
    }

}
