package ww.greendao.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ITEM.
 */
public class Item {

    private Long ItemID;
    private String ItemCode;
    private String ItemName;
    private Integer MinValue;
    private Integer MaxValue;
    private String Unit;
    private Integer DataLen;
    private Integer CarryMode;
    private Integer ItemType;
    private String MachineCode;
    private Integer IsEnable;
    private String Remark1;

    public Item() {
    }

    public Item(Long ItemID) {
        this.ItemID = ItemID;
    }

    public Item(Long ItemID, String ItemCode, String ItemName, Integer MinValue, Integer MaxValue, String Unit, Integer DataLen, Integer CarryMode, Integer ItemType, String MachineCode, Integer IsEnable, String Remark1) {
        this.ItemID = ItemID;
        this.ItemCode = ItemCode;
        this.ItemName = ItemName;
        this.MinValue = MinValue;
        this.MaxValue = MaxValue;
        this.Unit = Unit;
        this.DataLen = DataLen;
        this.CarryMode = CarryMode;
        this.ItemType = ItemType;
        this.MachineCode = MachineCode;
        this.IsEnable = IsEnable;
        this.Remark1 = Remark1;
    }

    public Long getItemID() {
        return ItemID;
    }

    public void setItemID(Long ItemID) {
        this.ItemID = ItemID;
    }

    public String getItemCode() {
        return ItemCode;
    }

    public void setItemCode(String ItemCode) {
        this.ItemCode = ItemCode;
    }

    public String getItemName() {
        return ItemName;
    }

    public void setItemName(String ItemName) {
        this.ItemName = ItemName;
    }

    public Integer getMinValue() {
        return MinValue;
    }

    public void setMinValue(Integer MinValue) {
        this.MinValue = MinValue;
    }

    public Integer getMaxValue() {
        return MaxValue;
    }

    public void setMaxValue(Integer MaxValue) {
        this.MaxValue = MaxValue;
    }

    public String getUnit() {
        return Unit;
    }

    public void setUnit(String Unit) {
        this.Unit = Unit;
    }

    public Integer getDataLen() {
        return DataLen;
    }

    public void setDataLen(Integer DataLen) {
        this.DataLen = DataLen;
    }

    public Integer getCarryMode() {
        return CarryMode;
    }

    public void setCarryMode(Integer CarryMode) {
        this.CarryMode = CarryMode;
    }

    public Integer getItemType() {
        return ItemType;
    }

    public void setItemType(Integer ItemType) {
        this.ItemType = ItemType;
    }

    public String getMachineCode() {
        return MachineCode;
    }

    public void setMachineCode(String MachineCode) {
        this.MachineCode = MachineCode;
    }

    public Integer getIsEnable() {
        return IsEnable;
    }

    public void setIsEnable(Integer IsEnable) {
        this.IsEnable = IsEnable;
    }

    public String getRemark1() {
        return Remark1;
    }

    public void setRemark1(String Remark1) {
        this.Remark1 = Remark1;
    }

}
