package ww.greendao.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STUDENT.
 */
public class Student {

    private Long StudentID;
    private String StudentCode;
    private String StudentName;
    private Integer Sex;
    private Long ClassID;
    private Long GradeID;
    private String IDCardNo;
    private String ICCardNo;
    private String DownloadTime;
    private String Remark1;
    private String Remark2;
    private String Remark3;

    public Student() {
    }

    public Student(Long StudentID) {
        this.StudentID = StudentID;
    }

    public Student(Long StudentID, String StudentCode, String StudentName, Integer Sex, Long ClassID, Long GradeID, String IDCardNo, String ICCardNo, String DownloadTime, String Remark1, String Remark2, String Remark3) {
        this.StudentID = StudentID;
        this.StudentCode = StudentCode;
        this.StudentName = StudentName;
        this.Sex = Sex;
        this.ClassID = ClassID;
        this.GradeID = GradeID;
        this.IDCardNo = IDCardNo;
        this.ICCardNo = ICCardNo;
        this.DownloadTime = DownloadTime;
        this.Remark1 = Remark1;
        this.Remark2 = Remark2;
        this.Remark3 = Remark3;
    }

    public Long getStudentID() {
        return StudentID;
    }

    public void setStudentID(Long StudentID) {
        this.StudentID = StudentID;
    }

    public String getStudentCode() {
        return StudentCode;
    }

    public void setStudentCode(String StudentCode) {
        this.StudentCode = StudentCode;
    }

    public String getStudentName() {
        return StudentName;
    }

    public void setStudentName(String StudentName) {
        this.StudentName = StudentName;
    }

    public Integer getSex() {
        return Sex;
    }

    public void setSex(Integer Sex) {
        this.Sex = Sex;
    }

    public Long getClassID() {
        return ClassID;
    }

    public void setClassID(Long ClassID) {
        this.ClassID = ClassID;
    }

    public Long getGradeID() {
        return GradeID;
    }

    public void setGradeID(Long GradeID) {
        this.GradeID = GradeID;
    }

    public String getIDCardNo() {
        return IDCardNo;
    }

    public void setIDCardNo(String IDCardNo) {
        this.IDCardNo = IDCardNo;
    }

    public String getICCardNo() {
        return ICCardNo;
    }

    public void setICCardNo(String ICCardNo) {
        this.ICCardNo = ICCardNo;
    }

    public String getDownloadTime() {
        return DownloadTime;
    }

    public void setDownloadTime(String DownloadTime) {
        this.DownloadTime = DownloadTime;
    }

    public String getRemark1() {
        return Remark1;
    }

    public void setRemark1(String Remark1) {
        this.Remark1 = Remark1;
    }

    public String getRemark2() {
        return Remark2;
    }

    public void setRemark2(String Remark2) {
        this.Remark2 = Remark2;
    }

    public String getRemark3() {
        return Remark3;
    }

    public void setRemark3(String Remark3) {
        this.Remark3 = Remark3;
    }

}
